name: CI

on:
  pull_request:

jobs:
  build:
    runs-on: [macos-latest]
    steps:
      - uses: swift-actions/setup-swift@v1.25.0
        with:
          swift-version: '5.7.2'
      - uses: actions/checkout@v4
      - name: Build
        run: swift build
